### ISSUE TITLE
v2.0 checklist

### ISSUE THREAD

**Issue by akre54** [jashkenas/underscore#1841]
Following 1.7.1, here's a list of things that would be great to get into v2.0. @megawac @braddunbar @michaelficarra let me know if I've missed something.
- [x] Remove minified file from package manager manifests. #1840
- [x] Align `_.extend` with ES6 `Object.assign` to ignore inherited properties. #1770
- [ ] Solidify `NaN` / `undefined` edge cases for comparators. #1768
- [ ] Add `_.slice`? #1758
- [x] Add support for changing `_.partial`'s placeholder. #1689
- [ ] `sortBy` multiple columns. #1751 
- [ ] Align intersection with union for object cases. #1583
- [x] Remove error throwing in _.reduce & _.reduceRight. #1858

**Comment by jgonggrijp** [comment]
Closing because this is very outdated and lists of issues are more conveniently managed with a milestone.
