### ISSUE TITLE
v1.7.1 checklist

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#1855]
Seeing as it's been more than two months *[updated]* since the release of 1.7.0 and Jeremy [mentioned](https://github.com/jashkenas/underscore/issues/1805#issuecomment-53939077) [plans](https://github.com/jashkenas/underscore/issues/1805#issuecomment-53939582) for a  1.7.1 it needs to be tackled or [dismissed](https://github.com/jashkenas/underscore/issues/1805#issuecomment-53941910).

@megawac @akre54 If it's to be tackled then it'll need a list of items to track for 1.7.1.

Something like:
* [x] _.extend (revert own property iteration)
* [ ] _.where (revert own property iteration)
* [ ] _.template param signature change
* [ ] ES5 Array method use

Related to #1841.

**Comment by OleksandrRakovets** [comment]
Hello guys, had anything happened with releases since August? Bower still downloads 1.7.0 which is 6 month old now.

Do you need any help?

**Comment by megawac** [comment]
Hey @OleksandrRakovets checkout #2012
